### ISSUE TITLE
UPGRADE FAILED: failed to create resource: Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string

### ISSUE THREAD

**Issue by roman-doubrava** [ToolJet/helm-charts#37]
Dear Toolset,

when performing helm install without any values.yaml we get the following error:

client.go:684: [debug] Looks like there are no changes for Service "tooljet"
client.go:693: [debug] Patch Deployment "tooljet-postgrest" in namespace tooljet
upgrade.go:476: [debug] warning: Upgrade "tooljet" failed: failed to create resource: Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
Error: UPGRADE FAILED: failed to create resource: Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
helm.go:84: [debug] Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
failed to create resource
helm.sh/helm/v3/pkg/kube.(*Client).Update.func1         helm.sh/helm/v3/pkg/kube/client.go:410
helm.sh/helm/v3/pkg/kube.ResourceList.Visit         helm.sh/helm/v3/pkg/kube/resource.go:32
helm.sh/helm/v3/pkg/kube.(*Client).Update         helm.sh/helm/v3/pkg/kube/client.go:394
helm.sh/helm/v3/pkg/action.(*Upgrade).releasingUpgrade         helm.sh/helm/v3/pkg/action/upgrade.go:418
runtime.goexit         runtime/asm_amd64.s:1695
UPGRADE FAILED
main.newUpgradeCmd.func2         helm.sh/helm/v3/cmd/helm/upgrade.go:240
github.com/spf13/cobra.(*Command).execute         github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC         github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute         github.com/spf13/cobra@v1.8.0/command.go:1039
main.main         helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main         runtime/proc.go:271
runtime.goexit         runtime/asm_amd64.s:1695

Best regards

**Comment by roman-doubrava** [comment]
Helm dry run gives following:
[debug-tooljet.yaml.txt](https://github.com/user-attachments/files/17745883/debug-tooljet.yaml.txt)

**Comment by adishM98** [comment]
Hi @roman-doubrava, 

We have fixed the issues and released a new version. Please update the helm chart and could you check once?
